function input_models = build_input_models()
%BUILD_INPUT_MODELS Return the three C/B input designs from the manuscript.
%
% Condition order:
% 1 FF initial, 2 FF immediate, 3 FF delayed,
% 4 UF initial, 5 UF immediate, 6 UF delayed,
% 7 SF initial, 8 SF immediate, 9 SF delayed.
%
% Rows are DCM inputs. Driving rows are used in C; repetition rows are used
% in B. Each model has the same six repetition modulators.

repetition_rows = [ ...
    0 1 0 0 0 0 0 0 0; ...
    0 0 1 0 0 0 0 0 0; ...
    0 0 0 0 1 0 0 0 0; ...
    0 0 0 0 0 1 0 0 0; ...
    0 0 0 0 0 0 0 1 0; ...
    0 0 0 0 0 0 0 0 1];

input_models = cell(3, 1);

input_models{1}.name = 'Model1_C1_All';
input_models{1}.label = 'Category-invariant input';
input_models{1}.contrast = [ ...
    1 1 1 1 1 1 1 1 1; ...
    repetition_rows];
input_models{1}.driver_rows = 1;

input_models{2}.name = 'Model2_C2_FaceScr';
input_models{2}.label = 'Category-specific face/scrambled input';
input_models{2}.contrast = [ ...
    1 1 1 1 1 1 0 0 0; ...
    0 0 0 0 0 0 1 1 1; ...
    repetition_rows];
input_models{2}.driver_rows = [1 2];

input_models{3}.name = 'Model3_C3_NoRep';
input_models{3}.label = 'Initial-presentation input only';
input_models{3}.contrast = [ ...
    1 0 0 1 0 0 0 0 0; ...
    0 0 0 0 0 0 1 0 0; ...
    repetition_rows];
input_models{3}.driver_rows = [1 2];
end

